name: Bookdown

on:
  push:
     branches:
       - main

jobs:
  build:
    name: 🏗 Build
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install R
        uses: r-lib/actions/setup-r@v2

      - name: Install Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install TinyTeX
        uses: r-lib/actions/setup-tinytex@v2

      - name: Install bookdown
        run: Rscript -e "install.packages(c('rmarkdown', 'bookdown'))"

      - name: Build book
        run: make all

      - uses: actions/upload-artifact@v2
        with:
          name: Bookdown
          path: Bookdown

  deploy:
    name: 📦 Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:

     - name: Download HTML
       uses: actions/download-artifact@v3
       with:
         name: Bookdown
         path: Bookdown

     - name: Deploy
       uses: peaceiris/actions-gh-pages@v3
       with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         publish_dir: Bookdown
